### ISSUE TITLE
Self type inside struct

### ISSUE THREAD

**Issue by Grompiler** [fabien14/ruban_led_connected#2]
https://github.com/fabien14/ruban_led_connected/blob/b7aa1fd71e80af4d6a910904e847d87af9ea0cb8/back_ruban_led_connected/src/framework_bluetooth/manager.rs#L14

Tu peux utiliser `Self` a l'interieur du impl, comme tu 'implementes le type lui meme'

**Comment by fabien14** [comment]
Yes j'avais un doute si je pouvais l'utiliser dans ce cas la.
Done, Merci
